language: python
python:
  - "3.6"
script:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls coverage"
  - 'cd draught_picks/ && coverage run --omit=home,manage.py manage.py test'
services:
  - "postgresql"
after_success:
  - "coveralls"
