language: python
python:
  - "3.6"
script:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls coverage"
  - "cd draught_picks/ && coverage run --source=beers,draught_picks,rest_api,users,description_parser --omit=manage.py,draught_picks/wsgi.py manage.py test"
services:
  - "postgresql"
after_success:
  - "coveralls"
