language: python
python:
  - "3.6"
env:
  - DJANGO_SETTINGS_MODULE="draught_picks.travis_settings"
before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
script:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls coverage"
  - "python manage.py migrate"
  - "cd draught_picks/ && coverage run --source=beers,draught_picks,rest_api,users,description_parser --omit=manage.py,draught_picks/wsgi.py,tf_model/ manage.py test"
services:
  - "postgresql"
after_success:
  - "coveralls"
